name: Atualizar Playlist M3U8

on:
  schedule:
    - cron: "0 9 * * *"  # 10h Portugal (9h UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Gerar nova playlist
        run: node playlist-generator/generate_playlist.js

      - name: Configurar Git
        run: |
          git config user.name "PlaylistBot"
          git config user.email "actions@github.com"

      - name: Commit & Push da playlist
        run: |
          git add video_playlist.m3u
          git diff --cached --quiet || git commit -m "Atualização automática da video_playlist.m3u8"
          git push
