name: Update streams

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  Update-streams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Run stream update script
        run: bash M3U/streams.sh

      - name: Setup git config
        run: |
          git config user.name "🚀 HAL 9000"
          git config user.email "actions@github.com"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd M3U
          git add M3UPT.m3u || echo "Nenhuma alteração para adicionar"
          git diff --cached --quiet || git commit -m "Update streams"
          git pull --rebase
          git push
