name: Atualizar Playlist M3U8

on:
  schedule:
    - cron: "0 9 * * *"  # 10h em Portugal
  workflow_dispatch:

permissions:
  contents: write

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Gerar nova playlist
        run: bash scripts/generate_segment.sh

      - name: Configurar Git
        run: |
          git config user.name "PlaylistBot"
          git config user.email "actions@github.com"

      - name: Commit & Push da playlist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add data/video_playlist.m3u
          git diff --cached --quiet || git commit -m "Atualização automática da video_playlist.m3u"
          git pull --rebase
          git push
